steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', 'hello-world', 'src/hello-world.go']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
         '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA',
         '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
         '-f', 'Dockerfile', '.']
    env: ['PROJECT_ROOT=github.com/kebab8902/m300/tree/master/LB3/GCB/src']
images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
